### ISSUE TITLE
Failure to install plugin. (Building)

### ISSUE THREAD

**Issue by iRayanKhan** [homebridge-plugins/homebridge-resideo#1]
Hi there,
I am currently using a Raspberry Pi 3B+ with 
node version: v12.11.1
npm version: 6.13.4

When I install this plugin after following the directions in the Readme, I get this error:
```
pi@raspberrypi:~ $ sudo npm i -g homebridge-honeywell-home
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-155f6178/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-155f6178/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-27T22_28_54_891Z-debug.log
```
I do not get this error install for other plugins, I also have ensured git is updated to the latest version. 
The npm logs show: 
( Sorry for the sake of me I can't get them to  open, I'm in the dir).

Troubleshooting steps:
- Update Git
- Follow ReadMe workarounds 
- Clear NPM cache
- Update Node and NPM

The next thing I want to try is attempting to install this on a different pi I have lying around. 

If I clone this plugin using git clone, then running ```npm install``` I get this:
```
pi@raspberrypi:~/homebridge-honeywell-home $ npm install

> arp-a@0.5.2 install /home/pi/homebridge-honeywell-home/node_modules/arp-a
> node-gyp rebuild

make: Entering directory '/home/pi/homebridge-honeywell-home/node_modules/arp-a/build'
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make: Leaving directory '/home/pi/homebridge-honeywell-home/node_modules/arp-a/build'

> socketwatcher@0.3.0 install /home/pi/homebridge-honeywell-home/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/home/pi/homebridge-honeywell-home/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
In file included from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Initialize(v8::Local<v8::Object>)’:
../socket_watcher.cpp:29:36: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   constructor.Reset(t->GetFunction());
                                    ^
In file included from /home/pi/.cache/node-gyp/12.11.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:5995:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
../socket_watcher.cpp:30:75: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   exports->Set(Nan::New("SocketWatcher").ToLocalChecked(), t->GetFunction());
                                                                           ^
In file included from /home/pi/.cache/node-gyp/12.11.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:5995:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:
../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Set(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../socket_watcher.cpp:116:32: error: no matching function for call to ‘v8::Value::Int32Value()’
   int fd = info[0]->Int32Value();
                                ^
In file included from /home/pi/.cache/node-gyp/12.11.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
In file included from ../../nan/nan.h:54,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
../socket_watcher.cpp: At global scope:
/home/pi/.cache/node-gyp/12.11.1/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.11.1/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../socket_watcher.cpp:143:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(socketwatcher, Init)
 ^~~~~~~~~~~
In file included from /home/pi/.cache/node-gyp/12.11.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pi/.cache/node-gyp/12.11.1/include/node/node_object_wrap.h:84:78:   required from here
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.cache/node-gyp/12.11.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [socketwatcher.target.mk:107: Release/obj.target/socketwatcher/socket_watcher.o] Error 1
make: Leaving directory '/home/pi/homebridge-honeywell-home/node_modules/socketwatcher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/homebridge-honeywell-home/node_modules/socketwatcher
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-27T22_47_05_422Z-debug.log
pi@raspberrypi:~/homebridge-honeywell-home $ 
```

**Comment by iRayanKhan** [comment]
Update:
Last step of installation in ReadMe worked on a different Pi.
Now the issue is controlling the thermostat, the instance says nothing when I update the value of the thermostat in the home app, and I changed the call back URL to the IP dress of my Pi since the 127 IP dress didn't work. I also changed it in the config of the Honeywell-setup-js. Now every time I do the Honeywell js setup, I get a new access and refresh code, so my theory is, does the plugin request a new one too? 

Also I know the readme says T9 thermostats, but the plugin seems to identify the T5 and says it's a "T5-T6".

**Comment by donavanbecker** [comment]
@iRayanKhan I had help from homespun on creating this plugin and have no coding experience. If you would like to submit a PR I will merge it.

**Comment by donavanbecker** [comment]
@iRayanKhan I was having issues install the plugin too and have had no luck lately installing it. thinking it has to do with having node 12.4 installed and it must of been created with an earlier version

**Comment by brunomisseeuw** [comment]
I seem to be having a similar issue on install 

```
pi@homeberrypi:/var/lib/homebridge/persist $ sudo npm install -g homebridge-honeywell-home
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-29T13_31_10_786Z-debug.log
```


[2019-12-29T13_31_10_786Z-debug.log](https://github.com/d0n4v4nb3ck3r/homebridge-honeywell-home/files/4008080/2019-12-29T13_31_10_786Z-debug.log)

**Comment by iRayanKhan** [comment]
Type CD
You seem to be in a whole different directory

**Comment by brunomisseeuw** [comment]
the current location / directory when running a command via sudo doesn't matter AFAIK ..

anyway, just to test/prove ..:

```
homebridge@homeberrypi:/var/lib/homebridge $ sudo npm install -g homebridge-honeywell-home
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-29T20_21_11_751Z-debug.log
```

**Comment by donavanbecker** [comment]
What version of npm are you running?

**Comment by brunomisseeuw** [comment]
@d0n4v4nb3ck3r 

```
homebridge@homeberrypi:~ $ npm -v
6.13.4
```

**Comment by brunomisseeuw** [comment]
and whilst at it node version below too

```
homebridge@homeberrypi:~ $ node -v
v12.14.0
```

**Comment by brunomisseeuw** [comment]
@d0n4v4nb3ck3r are you running older versions on the other RPI where the install did work?

**Comment by iRayanKhan** [comment]
I’m going to need to look at recompiling the plugin to use the latest node version.

**Comment by afalahi** [comment]
I’m curious as to why this plugin is needed? Since Honeywell supports HomeKit OOB

**Comment by mkellsy** [comment]
I looked into this and I found out that a dependency of the plugin is the cause.
[arp-a](https://www.npmjs.com/package/arp-a)

It is at the latest version 0.5.2 and it is 2 years old. It is used to scan arp tables in a network. There are other packages out there that don't require a Node-GYP build, which is what this is failing on.

I need to review the code to see what that dependency is used for. There are much newer packages that do the same thing. https://www.npmjs.com/search?q=keywords:arp

Also for those who are getting this error
```
npm ERR! syscall spawn git
```
This is because this plugin has a dependency that is hosted on GitHub, therefore you need to install git on your system.
```
sudo apt-get install -y git
```

Note. This plugin also requires libpcap-dev
```
sudo apt-get install -y libpcap-dev
```

**Comment by mkellsy** [comment]
I dug into the some more and it's the homespun package that uses arp-a. This will need to be forked and the arp observer functionality removed. This should be OK because your code only uses the roundtrip utility from homespun.

**Comment by mkellsy** [comment]
You can also remove the reliance on git by simply copying this file to your project https://github.com/homespun/hap-nodejs-community-types/blob/master/types.js

**Comment by mkellsy** [comment]
I created a pull request with these changes. It removes the dependencies on git, libpcap and node-gyp. So no building on install.
https://github.com/d0n4v4nb3ck3r/homebridge-honeywell-home/pull/2

Needs testing after you merge, I don't have a Honeywell thermostat.

**Comment by iRayanKhan** [comment]
> I’m curious as to why this plugin is needed? Since Honeywell supports HomeKit OOB

@afalahi Yes you are correct, some thermostats do support HomeKIt OOB, but my thermostats always show "No Response" in HomeKit, and it's a widespread issue. I have a T5 personally, and other Redditers have pointed this issue out too. No matter how many routers, resets, etc I've done, nothing works. The app always seems to work though so that's good.

**Comment by iRayanKhan** [comment]
@mkellsy Thank you! I will run these changes when I return home.

I appreciate the work you've done, will report back soon and merge it asap.

**Comment by brunomisseeuw** [comment]
FYI - after installing git as per @mkellsy suggestion

`sudo apt-get install -y git
`

(I did already have libpcap-dev installed), I do get fewer errors ..: 

```
root@homeberrypi:~# npm install -g homebridge-honeywell-home
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
npm ERR! 
npm ERR! fatal: cannot come back to cwd: Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T08_43_43_949Z-debug.log


root@homeberrypi:~# cat /root/.npm/_logs/2019-12-30T08_43_43_949Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-honeywell-home'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose npm-session c7bf66def1801981
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-honeywell-home 244ms (from cache)
8 silly pacote tag manifest for homebridge-honeywell-home@latest fetched in 359ms
9 timing stage:loadCurrentTree Completed in 503ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 21ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-honeywell-home@2.0.2 checking installable status
17 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Error while executing:
17 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData fatal: cannot come back to cwd: Permission denied
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData exited with error code: 128
18 http fetch GET 200 https://registry.npmjs.org/homespun-discovery 476ms (from cache)
19 silly pacote version manifest for homespun-discovery@0.3.4 fetched in 507ms
20 silly resolveWithNewModule homespun-discovery@0.3.4 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/debug 1000ms (from cache)
22 silly pacote range manifest for debug@~4.1.1 fetched in 1030ms
23 silly resolveWithNewModule debug@4.1.1 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/underscore 970ms (from cache)
25 silly pacote version manifest for underscore@1.9.1 fetched in 1009ms
26 silly resolveWithNewModule underscore@1.9.1 checking installable status
27 timing stage:rollbackFailedOptional Completed in 5ms
28 timing stage:runTopLevelLifecycles Completed in 1705ms
29 verbose stack Error: exited with error code: 128
29 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
29 verbose stack     at ChildProcess.emit (events.js:210:5)
29 verbose stack     at maybeClose (internal/child_process.js:1021:16)
29 verbose stack     at Socket.<anonymous> (internal/child_process.js:430:11)
29 verbose stack     at Socket.emit (events.js:210:5)
29 verbose stack     at Pipe.<anonymous> (net.js:659:12)
30 verbose cwd /root
31 verbose Linux 4.19.75-v7+
32 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-honeywell-home"
33 verbose node v12.14.0
34 verbose npm  v6.13.4
35 error Error while executing:
35 error /usr/bin/git ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
35 error
35 error fatal: cannot come back to cwd: Permission denied
35 error
35 error exited with error code: 128
36 verbose exit [ 1, true ]
```

I do have a T6 and can survive without this working in homebridge, but like - from what I read - also my T6's (I have two) are at occasions not reachable via Apple Home especially when I'm not at home and I'm connecting remotely to my Home (while all other accessories are reachable in the Home App).  When this happens I do have the Honeywell App as a fallback ..  If you guys want me to test something, let me know.. Happy to help where I can.

**Comment by donavanbecker** [comment]
T9 doesn’t have HomeKit

**Comment by donavanbecker** [comment]
I have published 2.2.2 on npm. Try it out and let me know. Hugh Thanks to @mkellsy!

**Comment by iRayanKhan** [comment]
Hi, does this support setting the thermostat temp now, or still read only?

**Comment by donavanbecker** [comment]
still read only, don't know much coding. I will try up probably will need help on getting writing to the api to work.

**Comment by mkellsy** [comment]
I'm here to help, just a busy guy. :)

**Comment by iRayanKhan** [comment]
There’s an existing honeywell plugin, but for TCC. That could be a base.

**Comment by donavanbecker** [comment]
@brunomisseeuw: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
