### ISSUE TITLE
Honeywell - "rate limit has been exhausted"

### ISSUE THREAD

**Issue by NogginTheNog** [homebridge-plugins/homebridge-resideo#106]
**Describe the bug**

The following is appearing in the logs when I click on the thermostat in the Home app

[3/18/2020, 17:42:35] [HoneywellHome] [DEBUG] Set TargetHeatingCoolingState: 1
[3/18/2020, 17:42:35] [HoneywellHome] Sending request to Honeywell API. mode: Heat, coolSetpoint: 10, heatSetpoint: 21
[3/18/2020, 17:42:35] [HoneywellHome] [DEBUG] {"mode":"Heat","thermostatSetpointStatus":"TemporaryHold","heatSetpoint":21,"coolSetpoint":10}
(node:28343) UnhandledPromiseRejectionWarning: StatusCodeError: 429 - {"code":"429.02.001","message":"rate limit has been exhausted"}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
(node:28343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**

Click on the Thermostat in the Home app.

**Expected behavior**

**Screenshots**

See above txt.

**Desktop (please complete the following information):**
Raspbian GNU/Linux Stretch (9)
Node.js Version v12.14.1
Npm Version v6.13.6

**Smartphone (please complete the following information):**
Device: iPhoneX
OS: iOS 13.3.1
Browser Home app
Version n/a

**Additional context**

**Comment by donavanbecker** [comment]
this is due to Honeywell's rate limit. I have requested for the increase but haven't got a response back yet. to help out everyone. make sure your ```TTL``` is set to ```1800```

**Comment by NogginTheNog** [comment]
Thanks I'll keep an eye ot it, just changed it to 1800

**Comment by donavanbecker** [comment]
@NogginTheNog thanks for doing that! did you have it set before that to something lower?

**Comment by NogginTheNog** [comment]
Yes, think it defaulted to a lower value with my first install homebridge-honeywell-home

**Comment by donavanbecker** [comment]
okay good to know. hopefully this helps all users. I will reachout Honeywell again.

**Comment by donavanbecker** [comment]
@NogginTheNog I have released 5.0.0 which force 1800 for TTL. Also lets you change the TTL if you supply your own customerSecret. This will so log differently if rate limit is reach too or invalid access token. Thanks to @oznu!

**Comment by donavanbecker** [comment]
@NogginTheNog: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
