### ISSUE TITLE
Fan settings not available

### ISSUE THREAD

**Issue by blazzik** [homebridge-plugins/homebridge-resideo#187]
Started getting this today...First it told me my token was expired, so I unlinked the account and re-linked it.  Now I get this upon homebridge startup...

```(node:15852) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"code":"InvalidInput"}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:15852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)```

**Comment by farrytheone** [comment]
I got the same problem.

 I unlinked the account and re-linked then it worked for a day or two. Today in the morning the heating was set to 25!!!!! the bug it self is not a problem but the heating is a bit problematic. :D


```
 [HoneywellHome] [DEBUG] Fetched update for Thermostat from Honeywell API: {"mode":"Heat","heatSetpoint":25,"coolSetpoint":10,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null} and Fan: {"message":"Fan settings not available"}
```

**Comment by donavanbecker** [comment]
@blazzik And @farrytheone what version are you on? And what thermostat model do you have?

**Comment by donavanbecker** [comment]
@farrytheone, all your log is telling me is that it fetch that from the Honeywell API and it was set at that. I would need more of your logs.

**Comment by farrytheone** [comment]
@donavanbecker I use the T6 homebridge-honeywell-home v5.1.1

I now re-linked the account, and put the log here.  Now you can see the setpoint heat is set to 20. that was the setting now. now for two days in the morning the setpoint was 25. Cooking us in the house. 


```[7/22/2020, 11:43:54 AM] [HoneywellHome] [DEBUG] Got access token: xxxxx
[7/22/2020, 11:43:54 AM] [HoneywellHome] [DEBUG] Found 2 locations
[7/22/2020, 11:43:54 AM] [HoneywellHome] [DEBUG] Getting devices for Home...
[7/22/2020, 11:43:55 AM] [HoneywellHome] Found 0 devices at Home.
[7/22/2020, 11:43:55 AM] [HoneywellHome] [DEBUG] Getting devices for My Home...
[7/22/2020, 11:43:55 AM] [HoneywellHome] Found 1 devices at My Home.
[7/22/2020, 11:43:55 AM] [HoneywellHome] Registering new device: Thermostat - LCC-B82CA03769E8
(node:1129) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"code":"InvalidInput"}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:1129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[7/22/2020, 11:43:56 AM] [HoneywellHome] [DEBUG] Fetched update for Thermostat from Honeywell API: {"mode":"Off","heatSetpoint":20,"coolSetpoint":10,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null} and Fan: {"message":"Fan settings not available"}
[7/22/2020, 11:43:56 AM] [HoneywellHome] [DEBUG] "Off"
[7/22/2020, 11:43:56 AM] [HoneywellHome] [DEBUG] {"message":"Fan settings not available"}
```

**Comment by donavanbecker** [comment]
@farrytheone can you take a picture of your thermostat inside the Honeywell app? also can you turn on homebridge debug so I can get more info of what is actually happening? I see that ```{"message":"Fan settings not available"}``` and would like to get more info about your device.

**Comment by farrytheone** [comment]
@donavanbecker debug mode is on, I replaced some ID's with a (xxxxxxxx) I don't have a cooling fan on my system. don't know if this is the problem? 

```
[7/22/2020, 2:14:23 PM] [HoneywellHome] Initializing HoneywellHome platform...
[7/22/2020, 2:14:23 PM] [HoneywellHome] TTL must be set to 1800 or higher unless you setup your own consumerSecret.
[7/22/2020, 2:14:23 PM] [HoneywellHome] [DEBUG] Config OK
[7/22/2020, 2:14:23 PM] Loading 1 accessories...
[7/22/2020, 2:14:23 PM] [HoneywellHome] [DEBUG] Loaded cached accessory Thermostat
Setup Payload:
X-HM://xxxxxxxxxxxx
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[7/22/2020, 2:14:24 PM] [HoneywellHome] [DEBUG] Got access token: xxxxxxxx
[7/22/2020, 2:14:25 PM] [HoneywellHome] [DEBUG] Found 2 locations
[7/22/2020, 2:14:25 PM] [HoneywellHome] [DEBUG] Getting devices for Home...
[7/22/2020, 2:14:25 PM] [HoneywellHome] []
[7/22/2020, 2:14:25 PM] [HoneywellHome] Found 0 devices at Home.
[7/22/2020, 2:14:25 PM] [HoneywellHome] [DEBUG] Getting devices for My Home...
[7/22/2020, 2:14:26 PM] [HoneywellHome] [
  {
    displayedOutdoorHumidity: 45,
    vacationHold: { enabled: false },
    currentSchedulePeriod: { day: 'Monday', period: 'P2' },
    scheduleCapabilities: { availableScheduleTypes: [Array], schedulableFan: false },
    scheduleType: { scheduleType: 'Timed', scheduleSubType: 'EMEA' },
    scheduleStatus: 'Pause',
    allowedTimeIncrements: 10,
    settings: {
      hardwareSettings: [Object],
      temperatureMode: [Object],
      specialMode: {},
      devicePairingEnabled: true
    },
    deviceClass: 'Thermostat',
    deviceType: 'Thermostat',
    deviceID: 'LCC-xxxxxxxxxxx',
    name: 'Thermostat',
    isAlive: true,
    isUpgrading: false,
    isProvisioned: true,
    macID: 'xxxxxxxxxxxxx',
    deviceSettings: {},
    service: { mode: 'Up' },
    deviceRegistrationDate: '2020-06-26T15:35:10.14',
    dataSyncStatus: 'Completed',
    units: 'Celsius',
    indoorTemperature: 23,
    outdoorTemperature: 19,
    allowedModes: [ 'Heat', 'Off' ],
    deadband: 0,
    hasDualSetpointStatus: false,
    minHeatSetpoint: 5,
    maxHeatSetpoint: 35,
    minCoolSetpoint: -18,
    maxCoolSetpoint: -18,
    changeableValues: {
      mode: 'Off',
      heatSetpoint: 20,
      coolSetpoint: 10,
      thermostatSetpointStatus: 'PermanentHold',
      heatCoolMode: 'Heat',
      endHeatSetpoint: null,
      endCoolSetpoint: null
    },
    operationStatus: {
      mode: 'EquipmentOff',
      fanRequest: false,
      circulationFanRequest: false
    },
    deviceModel: 'T5-T6'
  }
]
[7/22/2020, 2:14:26 PM] [HoneywellHome] Found 1 devices at My Home.
[7/22/2020, 2:14:26 PM] [HoneywellHome] Loading existing device: Thermostat - LCC-xxxxxxxx
(node:3266) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"code":"InvalidInput"}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:3266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[7/22/2020, 2:14:27 PM] [HoneywellHome] [DEBUG] Fetched update for Thermostat from Honeywell API: {"mode":"Off","heatSetpoint":20,"coolSetpoint":10,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null} and Fan: {"message":"Fan settings not available"}
[7/22/2020, 2:14:27 PM] [HoneywellHome] [DEBUG] "Off"
[7/22/2020, 2:14:27 PM] [HoneywellHome] [DEBUG] {"message":"Fan settings not available"}
```

**Comment by farrytheone** [comment]
I see there is a update for homebridge-config-ui don't know if its related?

https://github.com/oznu/homebridge-config-ui-x/issues/772

**Comment by donavanbecker** [comment]
@farrytheone nope not related. this is definitely this plugins issue. I will work on getting the plugin to see if it can find a fan or not. thanks for reporting. I will have this in the next update if I can find a good way to detect. would you be willing to test the beta when it is ready?

**Comment by farrytheone** [comment]
Thnx, yes if it helps I'm willing to help to test the beta

**Comment by donavanbecker** [comment]
> Thnx, yes if it helps I'm willing to help to test the beta

if you install v5.0.7. do you get these errors?

**Comment by farrytheone** [comment]
I'm having problems installing the older v5.0.7.

one moment....

**Comment by donavanbecker** [comment]
@farrytheone actually can you run the latest beta? I want to see what is being outputted for the yellow logging. 

```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```

**Comment by farrytheone** [comment]
@donavanbecker the log from the current version new instalment homebridge-honeywell-home v5.1.1 (no beta)
note to run de beta do ik have to uninstall the plugin before running te terminal command? 

```
[7/22/2020, 8:48:00 PM] [HoneywellHome] [DEBUG] Got access token: xxxxxx
[7/22/2020, 8:48:01 PM] [HoneywellHome] [DEBUG] Found 2 locations
[7/22/2020, 8:48:01 PM] [HoneywellHome] [DEBUG] Getting devices for Home...
[7/22/2020, 8:48:02 PM] [HoneywellHome] []
[7/22/2020, 8:48:02 PM] [HoneywellHome] Found 0 devices at Home.
[7/22/2020, 8:48:02 PM] [HoneywellHome] [DEBUG] Getting devices for My Home...
[7/22/2020, 8:48:02 PM] [HoneywellHome] [
  {
    displayedOutdoorHumidity: 58,
    vacationHold: { enabled: false },
    currentSchedulePeriod: { day: 'Monday', period: 'P4' },
    scheduleCapabilities: { availableScheduleTypes: [Array], schedulableFan: false },
    scheduleType: { scheduleType: 'Timed', scheduleSubType: 'EMEA' },
    scheduleStatus: 'Pause',
    allowedTimeIncrements: 10,
    settings: {
      hardwareSettings: [Object],
      temperatureMode: [Object],
      specialMode: {},
      devicePairingEnabled: true
    },
    deviceClass: 'Thermostat',
    deviceType: 'Thermostat',
    deviceID: 'LCC-xxxxxxx',
    name: 'Thermostat',
    isAlive: true,
    isUpgrading: false,
    isProvisioned: true,
    macID: 'xxxxxxxx',
    deviceSettings: {},
    service: { mode: 'Up' },
    deviceRegistrationDate: '2020-06-26T15:35:10.14',
    dataSyncStatus: 'Completed',
    units: 'Celsius',
    indoorTemperature: 23,
    outdoorTemperature: 17.5,
    allowedModes: [ 'Heat', 'Off' ],
    deadband: 0,
    hasDualSetpointStatus: false,
    minHeatSetpoint: 5,
    maxHeatSetpoint: 35,
    minCoolSetpoint: -18,
    maxCoolSetpoint: -18,
    changeableValues: {
      mode: 'Off',
      heatSetpoint: 18,
      coolSetpoint: 10,
      thermostatSetpointStatus: 'PermanentHold',
      heatCoolMode: 'Heat',
      endHeatSetpoint: null,
      endCoolSetpoint: null
    },
    operationStatus: {
      mode: 'EquipmentOff',
      fanRequest: false,
      circulationFanRequest: false
    },
    deviceModel: 'T5-T6'
  }
]
[7/22/2020, 8:48:02 PM] [HoneywellHome] Found 1 devices at My Home.
[7/22/2020, 8:48:02 PM] [HoneywellHome] Loading existing device: Thermostat - LCC-xxxxxxx
(node:648) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"code":"InvalidInput"}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[7/22/2020, 8:48:03 PM] [HoneywellHome] [DEBUG] Fetched update for Thermostat from Honeywell API: {"mode":"Off","heatSetpoint":18,"coolSetpoint":10,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null} and Fan: {"message":"Fan settings not available"}
[7/22/2020, 8:48:03 PM] [HoneywellHome] [DEBUG] "Off"
[7/22/2020, 8:48:03 PM] [HoneywellHome] [DEBUG] {"message":"Fan settings not available"}
[7/22/2020, 8:51:52 PM] [HoneywellHome] [DEBUG] Fetched update for Thermostat from Honeywell API: {"mode":"Off","heatSetpoint":18,"coolSetpoint":10,"thermostatSetpointStatus":"PermanentHold","heatCoolMode":"Heat","endHeatSetpoint":null,"endCoolSetpoint":null} and Fan: {"message":"Fan settings not available"}
[7/22/2020, 8:51:52 PM] [HoneywellHome] [DEBUG] "Off"
[7/22/2020, 8:51:52 PM] [HoneywellHome] [DEBUG] {"message":"Fan settings not available"}
```

**Comment by donavanbecker** [comment]
> the log from the current version new instalment homebridge-honeywell-home v5.1.1 (no beta)
> note to run de beta do ik have to uninstall the plugin before running te terminal command?
> 

@farrytheone you are going to get this log on v5.1.1, if you install v5.0.7 you wouldn't get this since thermostat fan wasn't implement then.

To install beta, you don't have to uninstall the plugin first. the beta will help me understand more, also you don't need debug on when you install the beta.

**Comment by donavanbecker** [comment]
@blazzik and @farrytheone I am wanting to release v6.0.0 that works correctly for users that don't have a fan setting, but I need users that don't have fans to test the betas so that I can make this work correctly for users like you. If I don't hear back from you in the next few days, I will release this version without a fix for this.

**Comment by farrytheone** [comment]
@donavanbecker at the moment I’m away from home. There where work related issues, sorry for not responding. Hope I can sent the debug log data ASAP.

If it’s a problem I can sent it after the release of V6.

**Comment by donavanbecker** [comment]
I have released v6.0.0. Once you are able to install and use it, it will help me get this fix out to you. So let me know once you can try it.

**Comment by donavanbecker** [comment]
@farrytheone, You may wanna test the beta #191

**Comment by donavanbecker** [comment]
@farrytheone 

I have released v6.1.0. You will want to test off that now.

**Comment by farrytheone** [comment]
@donavanbecker im still away from home. Stupid work 😩

I’m going to test it the moment I’m home. Have to get the first flight back tomorrow. 

But I’ll test it, and post the log

**Comment by farrytheone** [comment]
This are the moments you wander “do I need a remote vpn to my home network?”

**Comment by donavanbecker** [comment]
@farrytheone, Sounds Good!

**Comment by blazzik** [comment]
I can do some testing for you now... on 6.1.0 getting 

                {"code":400, "message":"The redirect URL provided does not match the redirect URL registered for the app."}
            
after attempting to relink again...

Debugging enabled, never see any errors in log

**Comment by donavanbecker** [comment]
@blazzik I need full logs. Debug would be most helpful and model of thermostat.

**Comment by farrytheone** [comment]
log file homebridge-honeywell-home v6.1.0

update now the thermostat is not found in the my home app. 

```
[8/3/2020, 7:12:12 PM] [HoneywellHome] Initializing HoneywellHome platform...
[8/3/2020, 7:12:12 PM] [HoneywellHome] Finished initializing platform: HoneywellHome
[8/3/2020, 7:12:12 PM] [HoneywellHome] Config OK
[8/3/2020, 7:12:12 PM] Loading 1 accessories...
[8/3/2020, 7:12:12 PM] [HoneywellHome] Executed didFinishLaunching callback
[8/3/2020, 7:12:12 PM] [HoneywellHome] Got access token: xxx
[8/3/2020, 7:12:12 PM] [HoneywellHome] New refresh token: xxx
[8/3/2020, 7:12:12 PM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[8/3/2020, 7:12:13 PM] [HoneywellHome] # of Locations Found: 2.
[8/3/2020, 7:12:13 PM] [HoneywellHome] Getting devices for Home...
[8/3/2020, 7:12:13 PM] [HoneywellHome] 2019423
[8/3/2020, 7:12:13 PM] [HoneywellHome] {
  locationID: 2019423,
  name: 'Home',
  streetAddress: '',
  city: '',
  country: 'NL',
  zipcode: 'xxxx',
  users: [
    {
      userID: xxx,
      username: 'xxxx@xxxxl',
      firstname: 'xxx',
      lastname: 'xxx',
      created: 1592944154,
      deleted: -62135596800,
      activated: true,
      connectedHomeAccountExists: true,
      locationRoleMapping: [Array],
      isOptOut: 'False',
      isCurrentUser: true
    }
  ],
  timeZone: 'W. Europe Standard Time',
  ianaTimeZone: 'Europe/Berlin',
  daylightSavingTimeEnabled: true,
  geoFenceEnabled: false,
  predictiveAIREnabled: false,
  comfortLevel: 0,
  geoFenceNotificationEnabled: false,
  geoFenceNotificationTypeId: 13,
  configuration: {
    faceRecognition: {
      enabled: false,
      maxPersons: 2,
      maxEtas: 2,
      maxEtaPersons: 1,
      schedules: [Array]
    }
  },
  devices: []
}
[8/3/2020, 7:12:13 PM] [HoneywellHome] # of Thermostats Found at Home: 0.
[8/3/2020, 7:12:13 PM] [HoneywellHome] Getting devices for My Home...
[8/3/2020, 7:12:13 PM] [HoneywellHome] 2019470
[8/3/2020, 7:12:13 PM] [HoneywellHome] {
  locationID: 2019470,
  name: 'My Home',
  streetAddress: 'xxxx xxxx',
  city: 'xxx',
  state: 'xxxx',
  country: 'xxxx',
  zipcode: 'xxxx xx',
  devices: [
    {
      displayedOutdoorHumidity: 70,
      vacationHold: [Object],
      currentSchedulePeriod: [Object],
      scheduleCapabilities: [Object],
      scheduleType: [Object],
      scheduleStatus: 'Pause',
      allowedTimeIncrements: 10,
      settings: [Object],
      deviceClass: 'Thermostat',
      deviceType: 'Thermostat',
      deviceID: 'LCC-B82CA03769E8',
      userDefinedDeviceName: 'Thermostat',
      name: 'Thermostat',
      isAlive: true,
      isUpgrading: false,
      isProvisioned: true,
      macID: 'xxxx',
      deviceSettings: {},
      service: [Object],
      deviceRegistrationDate: '2020-06-26T15:35:10.14',
      dataSyncStatus: 'Completed',
      units: 'Celsius',
      indoorTemperature: 23,
      outdoorTemperature: 19,
      allowedModes: [Array],
      deadband: 0,
      hasDualSetpointStatus: false,
      minHeatSetpoint: 5,
      maxHeatSetpoint: 35,
      minCoolSetpoint: -18,
      maxCoolSetpoint: -18,
      changeableValues: [Object],
      operationStatus: [Object],
      deviceModel: 'T5-T6'
    }
  ],
  users: [
    {
      userID: xxxx,
      username: 'xxx@xxxx',
      firstname: 'xxxx',
      lastname: 'xxx',
      created: 1592944154,
      deleted: -62135596800,
      activated: true,
      connectedHomeAccountExists: true,
      locationRoleMapping: [Array],
      isOptOut: 'False',
      isCurrentUser: true
    }
  ],
  timeZone: 'W. Europe Standard Time',
  ianaTimeZone: 'Europe/Berlin',
  daylightSavingTimeEnabled: true,
  geoFenceEnabled: false,
  predictiveAIREnabled: false,
  comfortLevel: 0,
  geoFenceNotificationEnabled: false,
  geoFenceNotificationTypeId: 13,
  configuration: {
    faceRecognition: {
      enabled: false,
      maxPersons: 10,
      maxEtas: 2,
      maxEtaPersons: 1,
      schedules: [Array]
    }
  },
  stateName: 'xxxx'
}
[8/3/2020, 7:12:13 PM] [HoneywellHome] # of Thermostats Found at My Home: 1.
[8/3/2020, 7:12:13 PM] [HoneywellHome] {
  displayedOutdoorHumidity: 70,
  vacationHold: { enabled: false },
  currentSchedulePeriod: { day: 'Monday', period: 'P3' },
  scheduleCapabilities: {
    availableScheduleTypes: [ 'None', 'Geofenced', 'TimedEmea' ],
    schedulableFan: false
  },
  scheduleType: { scheduleType: 'Timed', scheduleSubType: 'EMEA' },
  scheduleStatus: 'Pause',
  allowedTimeIncrements: 10,
  settings: {
    hardwareSettings: { brightness: 3, maxBrightness: 5 },
    temperatureMode: { air: true },
    specialMode: {},
    devicePairingEnabled: true
  },
  deviceClass: 'Thermostat',
  deviceType: 'Thermostat',
  deviceID: 'LCC-B82CA03769E8',
  userDefinedDeviceName: 'Thermostat',
  name: 'Thermostat',
  isAlive: true,
  isUpgrading: false,
  isProvisioned: true,
  macID: 'B82CA03769E8',
  deviceSettings: {},
  service: { mode: 'Up' },
  deviceRegistrationDate: '2020-06-26T15:35:10.14',
  dataSyncStatus: 'Completed',
  units: 'Celsius',
  indoorTemperature: 23,
  outdoorTemperature: 19,
  allowedModes: [ 'Heat', 'Off' ],
  deadband: 0,
  hasDualSetpointStatus: false,
  minHeatSetpoint: 5,
  maxHeatSetpoint: 35,
  minCoolSetpoint: -18,
  maxCoolSetpoint: -18,
  changeableValues: {
    mode: 'Heat',
    heatSetpoint: 20,
    coolSetpoint: 10,
    thermostatSetpointStatus: 'PermanentHold',
    heatCoolMode: 'Heat',
    endHeatSetpoint: null,
    endCoolSetpoint: null
  },
  operationStatus: {
    mode: 'EquipmentOff',
    fanRequest: false,
    circulationFanRequest: false
  },
  deviceModel: 'T5-T6'
}
[8/3/2020, 7:12:13 PM] [HoneywellHome] LCC-B82CA03769E8
[8/3/2020, 7:12:13 PM] [HoneywellHome] Failed to refresh access token. Cannot read property 'allowedModes' of undefined
```

**Comment by donavanbecker** [comment]
@farrytheone and @blazzik can you try the new beta? and submit logs, Thanks!

To Install
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```
To Revert
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@latest
```

**Comment by donavanbecker** [comment]
@blazzik, @farrytheone: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
