### ISSUE TITLE
TCC - Round Devices

### ISSUE THREAD

**Issue by roficas** [homebridge-plugins/homebridge-resideo#209]
**Describe The Bug:**
In debug mode, the logs show my 3 devices are offline, but I can see and control them using the Honeywell Home App.

**To Reproduce:**
I just authenticated using the UI (and double checked that the config is in the file) and when home bridge starts it shows in the log the message in the title for each one of the 3 thermostats I have here.

**Expected behavior:**
Thermostats should be listed in the home Bridge device settings (and not ignored)

**Logs:**

```
6/6/2020, 12:04:31 PM] [HoneywellHome] [DEBUG] Getting devices for Lylebrooke...
[6/6/2020, 12:04:32 PM] [HoneywellHome] Found 3 devices at Lylebrooke.
[6/6/2020, 12:04:32 PM] [HoneywellHome] [DEBUG] Ignoring device named 1st as it is offline.
[6/6/2020, 12:04:32 PM] [HoneywellHome] [DEBUG] Ignoring device named 2nd as it is offline.
[6/6/2020, 12:04:32 PM] [HoneywellHome] [DEBUG] Ignoring device named 3rd as it is offline.

```

**Homebridge Config:**

```json

{
            "name": "HoneywellHome",
            "credentials": {
                "consumerKey": "token",
                "refreshToken": "refresh_tokey",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "ttl": 60,
                "debug": true
            },
            "platform": "HoneywellHome"
        }

```

**Screenshots:**
Not applicable

**Environment:**

* **Node.js Version**: 12.18.0
* **NPM Version**: 6.14.4
* **Homebridge Version**: latest (1.1.0)
* **Homebridge Honeywell Home Version**: latest (just installed)
* **Homebridge Config UI X Plugin Version**: latest
* **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@roficas I have now release v7.0.1 which even has more fixes for fans and possible TCC devices. Let me know.

**Comment by roficas** [comment]
Hi. Sorry for taking so long. My trip was longer than expected.

Below is the log I got Monday. I tried to reconfigure everything, but still the same issue on the refresh token... 

```
[8/31/2020, 9:31:09 AM] [HoneywellHome] Initializing HoneywellHome platform...
[8/31/2020, 9:31:09 AM] [HoneywellHome] Finished initializing platform: HoneywellHome
[8/31/2020, 9:31:09 AM] [HoneywellHome] Config OK
[8/31/2020, 9:31:09 AM] [HoneywellHome] Loading accessory from cache: 1st
[8/31/2020, 9:31:09 AM] [HoneywellHome] Loading accessory from cache: 2nd
[8/31/2020, 9:31:09 AM] [HoneywellHome] Loading accessory from cache: 3rd
[8/31/2020, 9:31:09 AM] [HoneywellHome] Executed didFinishLaunching callback
[8/31/2020, 9:31:10 AM] [HoneywellHome] Got access token: xxx
[8/31/2020, 9:31:10 AM] [HoneywellHome] New refresh token: xxx
[8/31/2020, 9:31:10 AM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[8/31/2020, 9:31:10 AM] [HoneywellHome] # of Locations Found: 1.
[8/31/2020, 9:31:10 AM] [HoneywellHome] Getting devices for Lylebrooke...
[8/31/2020, 9:31:10 AM] [HoneywellHome] 1359757
[8/31/2020, 9:31:10 AM] [HoneywellHome] {
  locationID: xxx,
  name: 'xxx',
  country: 'US',
  zipcode: 'xxx',
  devices: [
    {
      thermostatVersion: '02.02.20.60',
      scheduleStatus: 'Resume',
      allowedTimeIncrements: 15,
      settings: [Object],
      deviceClass: 'Thermostat',
      deviceType: 'Thermostat',
      deviceID: 'TCC-xxx',
      userDefinedDeviceName: '1st',
      name: '1st',
      schedule: [Object],
      isAlive: true,
      isUpgrading: false,
      isProvisioned: false,
      macID: 'xxx',
      deviceSettings: {},
      service: [Object],
      deviceRegistrationDate: '2019-07-20T01:13:43.2266667',
      dataSyncStatus: 'UnKnown',
      units: 'Fahrenheit',
      indoorTemperature: 79,
      outdoorTemperature: 70,
      allowedModes: [Array],
      deadband: 0,
      hasDualSetpointStatus: false,
      minHeatSetpoint: 40,
      maxHeatSetpoint: 99,
      minCoolSetpoint: 40,
      maxCoolSetpoint: 99,
      changeableValues: [Object],
      operationStatus: [Object],
      smartAway: [Object],
      indoorHumidity: 48,
      indoorHumidityStatus: 'Measured',
      deviceModel: 'Round'
    },
    {
      thermostatVersion: '02.02.20.60',
      scheduleStatus: 'Resume',
      allowedTimeIncrements: 15,
      settings: [Object],
      deviceClass: 'Thermostat',
      deviceType: 'Thermostat',
      deviceID: 'TCC-xxx',
      userDefinedDeviceName: '2nd',
      name: '2nd',
      schedule: [Object],
      isAlive: true,
      isUpgrading: false,
      isProvisioned: false,
      macID: 'xxx',
      deviceSettings: {},
      service: [Object],
      deviceRegistrationDate: '2020-06-04T12:46:19.35',
      dataSyncStatus: 'UnKnown',
      units: 'Fahrenheit',
      indoorTemperature: 79,
      outdoorTemperature: 70,
      allowedModes: [Array],
      deadband: 0,
      hasDualSetpointStatus: false,
      minHeatSetpoint: 40,
      maxHeatSetpoint: 99,
      minCoolSetpoint: 40,
      maxCoolSetpoint: 99,
      changeableValues: [Object],
      operationStatus: [Object],
      smartAway: [Object],
      indoorHumidity: 48,
      indoorHumidityStatus: 'Measured',
      deviceModel: 'Round'
    },
    {
      thermostatVersion: '02.02.20.60',
      scheduleStatus: 'Resume',
      allowedTimeIncrements: 15,
      settings: [Object],
      deviceClass: 'Thermostat',
      deviceType: 'Thermostat',
      deviceID: 'TCC-xxx',
      userDefinedDeviceName: '3rd',
      name: '3rd',
      schedule: [Object],
      isAlive: true,
      isUpgrading: false,
      isProvisioned: false,
      macID: 'xxx',
      deviceSettings: {},
      service: [Object],
      deviceRegistrationDate: '2019-08-13T20:14:14.54',
      dataSyncStatus: 'UnKnown',
      units: 'Fahrenheit',
      indoorTemperature: 80,
      outdoorTemperature: 70,
      allowedModes: [Array],
      deadband: 0,
      hasDualSetpointStatus: false,
      minHeatSetpoint: 40,
      maxHeatSetpoint: 99,
      minCoolSetpoint: 40,
      maxCoolSetpoint: 99,
      changeableValues: [Object],
      operationStatus: [Object],
      smartAway: [Object],
      indoorHumidity: 46,
      indoorHumidityStatus: 'Measured',
      deviceModel: 'Round'
    }
  ],
  users: [
    {
      userID: xx,
      username: 'xxx@me.com',
      firstname: 'xx',
      lastname: 'xx',
      created: 1491265966,
      deleted: -62135596800,
      activated: true,
      connectedHomeAccountExists: true,
      locationRoleMapping: [Array],
      isOptOut: '',
      isCurrentUser: true
    },
    {
      userID: xx,
      username: 'xxx@gmail.com',
      firstname: 'xxx',
      lastname: 'xxx',
      created: 1487555607,
      deleted: -62135596800,
      activated: true,
      connectedHomeAccountExists: true,
      locationRoleMapping: [Array],
      isOptOut: '',
      isCurrentUser: false
    }
  ],
  timeZoneId: 'Eastern',
  timeZone: 'Eastern Standard Time',
  ianaTimeZone: 'America/New_York',
  daylightSavingTimeEnabled: true,
  geoFences: [
    {
      geofenceEnabled: true,
      geoFenceID: xx,
      latitude: xx.86711,
      longitude: -xx.4931641,
      radius: 1609.86633,
      geoOccupancy: [Object],
      geoFenceNotificationEnabled: false
    }
  ],
  geoFenceEnabled: true,
  predictiveAIREnabled: false,
  comfortLevel: 0,
  geoFenceNotificationEnabled: false,
  geoFenceNotificationTypeId: 13,
  configuration: {
    faceRecognition: {
      enabled: false,
      maxPersons: 2,
      maxEtas: 2,
      maxEtaPersons: 1,
      schedules: [Array]
    }
  }
}
[8/31/2020, 9:31:10 AM] [HoneywellHome] # of Thermostats Found at Lylebrooke: 3.
[8/31/2020, 9:31:10 AM] [HoneywellHome] {
  thermostatVersion: '02.02.20.60',
  scheduleStatus: 'Resume',
  allowedTimeIncrements: 15,
  settings: {
    homeSetPoints: { homeHeatSP: 70, homeCoolSP: 76, units: 'Fahrenheit' },
    awaySetPoints: {
      awayHeatSP: 68,
      awayCoolSP: 72,
      smartCoolSP: 80,
      smartHeatSP: 55,
      useAutoSmart: true,
      units: 'Fahrenheit'
    },
    hardwareSettings: { brightness: 3, volume: 10, maxBrightness: 10, maxVolume: 10 },
    fan: {
      allowedModes: [Array],
      changeableValues: [Object],
      fanRunning: false
    },
    temperatureMode: { feelsLike: true, air: true },
    specialMode: { autoChangeoverActive: true, emergencyHeatActive: false }
  },
  deviceClass: 'Thermostat',
  deviceType: 'Thermostat',
  deviceID: 'TCC-xxx',
  userDefinedDeviceName: '1st',
  name: '1st',
  schedule: { scheduleType: 'Geofence' },
  isAlive: true,
  isUpgrading: false,
  isProvisioned: false,
  macID: 'xxx',
  deviceSettings: {},
  service: { mode: 'Up' },
  deviceRegistrationDate: '2019-07-20T01:13:43.2266667',
  dataSyncStatus: 'UnKnown',
  units: 'Fahrenheit',
  indoorTemperature: 79,
  outdoorTemperature: 70,
  allowedModes: [ 'Cool', 'Heat', 'Off' ],
  deadband: 0,
  hasDualSetpointStatus: false,
  minHeatSetpoint: 40,
  maxHeatSetpoint: 99,
  minCoolSetpoint: 40,
  maxCoolSetpoint: 99,
  changeableValues: {
    mode: 'Auto',
    autoChangeoverActive: true,
    emergencyHeatActive: false,
    heatSetpoint: 72,
    coolSetpoint: 79,
    heatCoolMode: 'Cool'
  },
  operationStatus: { mode: 'EquipmentOff' },
  smartAway: {
    active: false,
    timeOfDay: '00:00:00',
    durationInHours: 0,
    durationInDays: 0,
    lastUsedFormat: 'TimeOfDay',
    endsIn: '2000-01-01T00:00:00-05:00'
  },
  indoorHumidity: 48,
  indoorHumidityStatus: 'Measured',
  deviceModel: 'Round'
}
[8/31/2020, 9:31:10 AM] [HoneywellHome] TCC-xxx
[8/31/2020, 9:31:11 AM] [HoneywellHome] {
  thermostatVersion: '02.02.20.60',
  scheduleStatus: 'Resume',
  allowedTimeIncrements: 15,
  settings: {
    homeSetPoints: { homeHeatSP: 70, homeCoolSP: 76, units: 'Fahrenheit' },
    awaySetPoints: {
      awayHeatSP: 68,
      awayCoolSP: 72,
      smartCoolSP: 80,
      smartHeatSP: 55,
      useAutoSmart: true,
      units: 'Fahrenheit'
    },
    hardwareSettings: { brightness: 3, volume: 10, maxBrightness: 10, maxVolume: 10 },
    fan: {
      allowedModes: [Array],
      changeableValues: [Object],
      fanRunning: false
    },
    temperatureMode: { feelsLike: true, air: true },
    specialMode: { autoChangeoverActive: true, emergencyHeatActive: false }
  },
  deviceClass: 'Thermostat',
  deviceType: 'Thermostat',
  deviceID: 'TCC-xxx',
  userDefinedDeviceName: '1st',
  name: '1st',
  schedule: { scheduleType: 'Geofence' },
  isAlive: true,
  isUpgrading: false,
  isProvisioned: false,
  macID: 'xxx',
  deviceSettings: {},
  service: { mode: 'Up' },
  dataSyncStatus: 'UnKnown',
  units: 'Fahrenheit',
  indoorTemperature: 79,
  outdoorTemperature: 70,
  allowedModes: [ 'Cool', 'Heat', 'Off' ],
  deadband: 0,
  hasDualSetpointStatus: false,
  minHeatSetpoint: 40,
  maxHeatSetpoint: 99,
  minCoolSetpoint: 40,
  maxCoolSetpoint: 99,
  changeableValues: {
    mode: 'Auto',
    autoChangeoverActive: true,
    emergencyHeatActive: false,
    heatSetpoint: 72,
    coolSetpoint: 79,
    heatCoolMode: 'Cool'
  },
  operationStatus: { mode: 'EquipmentOff' },
  smartAway: {
    active: false,
    timeOfDay: '00:00:00',
    durationInHours: 0,
    durationInDays: 0,
    lastUsedFormat: 'TimeOfDay',
    endsIn: '2000-01-01T00:00:00-05:00'
  },
  indoorHumidity: 48,
  indoorHumidityStatus: 'Measured',
  deviceModel: 'Round'
}
[8/31/2020, 9:31:11 AM] [HoneywellHome] TCC-2733987
[8/31/2020, 9:31:11 AM] [HoneywellHome] TCC UDID: 1stTCC-2733987
[8/31/2020, 9:31:11 AM] [HoneywellHome] Restoring existing accessory from cache: 1st
[8/31/2020, 9:31:11 AM] [HoneywellHome] Failed to refresh access token. Cannot read property 'schedulableFan' of undefined
```

**Comment by donavanbecker** [comment]
@roficas and is this with `v7.0.1`?

**Comment by donavanbecker** [comment]
@roficas can you test the latest beta: `v7.0.2-beta.50`?

I added this [warning](https://github.com/donavanbecker/homebridge-honeywell-home/blob/3b195398289258b6b08d4c790444fb67958ae611/src/platform.ts#L500), you should be able to run your homebridge without debug mode. I need the log on this warning. It should show as yellow.

**Comment by roficas** [comment]
here it is:

```
[9/2/2020, 4:59:09 PM] [HoneywellHome] Initializing HoneywellHome platform...
[9/2/2020, 4:59:09 PM] Loading 1 accessories...
[9/2/2020, 4:59:09 PM] [HoneywellHome] Loading accessory from cache: 1st
[9/2/2020, 4:59:09 PM] [HoneywellHome] Loading accessory from cache: 2nd
[9/2/2020, 4:59:09 PM] [HoneywellHome] Loading accessory from cache: 3rd
[9/2/2020, 4:59:10 PM] [HoneywellHome] Got access token: xxx
[9/2/2020, 4:59:10 PM] [HoneywellHome] New refresh token: xxx
[9/2/2020, 4:59:10 PM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[9/2/2020, 4:59:10 PM] [HoneywellHome] Getting devices for Lylebrooke...
[9/2/2020, 4:59:11 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: false
}
[9/2/2020, 4:59:11 PM] [HoneywellHome] Restoring existing accessory from cache: 1st
[9/2/2020, 4:59:11 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: true
}
[9/2/2020, 4:59:11 PM] [HoneywellHome] Restoring existing accessory from cache: 2nd
[9/2/2020, 4:59:11 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: false
}
[9/2/2020, 4:59:11 PM] [HoneywellHome] Restoring existing accessory from cache: 3rd
[9/2/2020, 4:59:12 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: false
}
[9/2/2020, 4:59:12 PM] [HoneywellHome] Restoring existing accessory from cache: 1st
[9/2/2020, 4:59:12 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: true
}
[9/2/2020, 4:59:12 PM] [HoneywellHome] Restoring existing accessory from cache: 2nd
[9/2/2020, 4:59:12 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: false
}
[9/2/2020, 4:59:12 PM] [HoneywellHome] Restoring existing accessory from cache: 3rd
[9/2/2020, 4:59:12 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: false
}
[9/2/2020, 4:59:12 PM] [HoneywellHome] Restoring existing accessory from cache: 1st
[9/2/2020, 4:59:12 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: true
}
[9/2/2020, 4:59:12 PM] [HoneywellHome] Restoring existing accessory from cache: 2nd
[9/2/2020, 4:59:12 PM] [HoneywellHome] {
  allowedModes: [ 'Auto', 'On', 'Circulate' ],
  changeableValues: { mode: 'Auto' },
  fanRunning: false
}
[9/2/2020, 4:59:12 PM] [HoneywellHome] Restoring existing accessory from cache: 3rd
```

**Comment by roficas** [comment]
one more thing: I tried to set the temperature, simple test, and it made homebridge restart:

```
[9/2/2020, 5:04:27 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at ThermostatTCC.setTargetHeatingCoolingState (/usr/lib/node_modules/homebridge-honeywell-home/src/thermostatTCC.ts:338:5)
    at Characteristic.emit (events.js:327:22)
    at Characteristic.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
uncaughtException: This callback function has already been called by someone else; it can only be called one time.
uncaughtException: This callback function has already been called by someone else; it can only be called one time.
[9/2/2020, 5:04:27 PM] [HoneywellHome] Sending request to Honeywell API. mode: Auto, coolSetpoint: 78, heatSetpoint: 72
[9/2/2020, 5:04:27 PM] [HoneywellHome] Sending request to Honeywell API. mode: Auto, coolSetpoint: 78, heatSetpoint: 72
[9/2/2020, 5:04:27 PM] Got SIGTERM, shutting down Homebridge...
[9/2/2020, 5:04:28 PM] [HoneywellHome] Request failed with status code 400
[9/2/2020, 5:04:28 PM] [HoneywellHome] Request failed with status code 400
[9/2/2020, 5:04:32 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/2/2020, 5:04:37 PM] [HB Supervisor] Restarting Homebridge...
[9/2/2020, 5:04:37 PM] [HB Supervisor] Started Homebridge v1.1.2 with PID: 4706
```

**Comment by donavanbecker** [comment]
Yeah working with someone else on discord that has TCC and changed something. So that is probably why that happened On the latest beta

**Comment by donavanbecker** [comment]
Okay, I totally re-did the device discovery, can you test the latest beta? `v7.2.1-beta.0`

**Comment by donavanbecker** [comment]
@roficas , I just pushed out a new beta. can you test it?

To Install:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```
To Revert:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@latest
```

**Comment by roficas** [comment]
here is the log:

```
[9/9/2020, 10:16:26 AM] [HoneywellHome] Initializing HoneywellHome platform...
[9/9/2020, 10:16:26 AM] [HoneywellHome] Room Sensors will only display as Room Sensors.
[9/9/2020, 10:16:26 AM] Loading 1 accessories...
[9/9/2020, 10:16:26 AM] [HoneywellHome] Loading accessory from cache: 1st
[9/9/2020, 10:16:26 AM] [HoneywellHome] Loading accessory from cache: 2nd
[9/9/2020, 10:16:26 AM] [HoneywellHome] Loading accessory from cache: 3rd
[9/9/2020, 10:16:27 AM] [HoneywellHome] Got access token: xxx
[9/9/2020, 10:16:27 AM] [HoneywellHome] New refresh token: xxx
[9/9/2020, 10:16:27 AM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[9/9/2020, 10:16:30 AM] [HoneywellHome] Total Locations Found: 1
[9/9/2020, 10:16:30 AM] [HoneywellHome] Getting devices for Lylebrooke...
[9/9/2020, 10:16:30 AM] [HoneywellHome] Total Devices Found at Lylebrooke: 3
[9/9/2020, 10:16:30 AM] [HoneywellHome] Adding new accessory: 1st Round Thermostat
(node:10225) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'schedulableFan' of undefined
    at Round.parseStatus (/usr/lib/node_modules/homebridge-honeywell-home/src/Thermostats/Round.ts:222:42)
    at new Round (/usr/lib/node_modules/homebridge-honeywell-home/src/Thermostats/Round.ts:102:10)
    at HoneywellHomePlatform.Round (/usr/lib/node_modules/homebridge-honeywell-home/src/platform.ts:656:7)
    at HoneywellHomePlatform.discoverDevices (/usr/lib/node_modules/homebridge-honeywell-home/src/platform.ts:435:20)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/src/platform.ts:83:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10225) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10225) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

sorry for the delay - I'll be more responsive from now on :)

**Comment by donavanbecker** [comment]
sorry about this. that is an easy fix. I am working on pushing a mother beta in a little bit that should fix that error.

**Comment by donavanbecker** [comment]
> 
> To Install:
> 
> ```
> sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
> ```
> 
> To Revert:
> 
> ```
> sudo npm install -g --unsafe-perm homebridge-honeywell-home@latest
> ```

@roficas can you try the latest beta? ``v7.2.2-beta.12``

**Comment by roficas** [comment]
It loaded fine. When I open and try to set any temperature, I get errors:

Opening the accessory
```
[9/14/2020, 1:56:17 PM] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 79, heatSetpoint: 72
[9/14/2020, 1:56:18 PM] [HoneywellHome] "Request failed with status code 400"
```

Setting the temperature
```
[9/14/2020, 1:56:23 PM] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 77, heatSetpoint: 72
[9/14/2020, 1:56:24 PM] [HoneywellHome] "Request failed with status code 400"
```

**Comment by donavanbecker** [comment]
@roficas would you feel comfortable with sharing one of your thermostats through the Honeywell Home app? so that I can do some testing.

If so reach out to me on the [Homebridge Discord Server](https://discord.gg/8fpZA4S).

**Comment by donavanbecker** [comment]
@roficas I am having a hard time with TCC devices. Honeywell doesn't have much detail of it on their website. I am testing with a TCC thermostat, but it is not a Round thermostat.

**Comment by roficas** [comment]
I'm guessing here there is something to do with the auto mode, where there is a temperature range. When I add the thermostats to HomeKit directly, it doesn't show the range.

**Comment by roficas** [comment]
it's weird because I can set the fan to circulate but not the temperature or the mode.

**Comment by donavanbecker** [comment]
can you reach out to me on discord?
