### ISSUE TITLE
Plugin attempting to add a sensor twice

### ISSUE THREAD

**Issue by ericingravity** [homebridge-plugins/homebridge-resideo#310]
**Describe The Bug:**

Added Honeywell Sensor ([link](https://www.honeywellstore.com/store/products/honeywell-smart-room-sensor-for-t9t10-thermostats-rchtsensor-1pk.htm)) to a thermostat. Homebridge won't start due to errors. Looks like plugin is trying to add the sensor twice and fails. I have tried clearing Homebridge caches several times.

**To Reproduce:**

1. Added Honeywell Sensor to a thermostat
2. Restart Homebridge

**Expected behavior:**

Sensor is identified and added (once). No errors.

**Logs:**

[25/11/2020, 23:11:49] Got SIGTERM, shutting down Homebridge...
[25/11/2020, 23:11:54] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[25/11/2020, 23:11:59] [HB Supervisor] Restarting Homebridge...
[25/11/2020, 23:11:59] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[25/11/2020, 23:11:59] [HB Supervisor] Started Homebridge v1.2.3 with PID: 1124
[25/11/2020, 23:12:00] Loaded config.json with 0 accessories and 3 platforms.
[25/11/2020, 23:12:00] ---
[25/11/2020, 23:12:00] Loaded plugin: homebridge-config-ui-x@4.34.0
[25/11/2020, 23:12:00] Registering platform 'homebridge-config-ui-x.config'
[25/11/2020, 23:12:00] ---
[25/11/2020, 23:12:01] Loaded plugin: homebridge-honeywell-home@8.1.1
[25/11/2020, 23:12:01] Registering platform 'homebridge-honeywell-home.HoneywellHome'
[25/11/2020, 23:12:01] ---
[25/11/2020, 23:12:01] Loaded plugin: homebridge-myq@2.3.5
[25/11/2020, 23:12:01] Registering platform 'homebridge-myq.myQ'
[25/11/2020, 23:12:01] ---
[25/11/2020, 23:12:01] Loading 3 platforms...
[25/11/2020, 23:12:01] [Config] Initializing config platform...
[25/11/2020, 23:12:01] [Config] Running in Service Mode
[25/11/2020, 23:12:01] [myQ] Initializing myQ platform...
[25/11/2020, 23:12:01] [HoneywellHome] Initializing HoneywellHome platform...
[25/11/2020, 23:12:01] [HoneywellHome] Finished initializing platform: HoneywellHome
[25/11/2020, 23:12:01] [HoneywellHome] Only Displaying Room Sensors.
[25/11/2020, 23:12:01] [HoneywellHome] Config OK
[25/11/2020, 23:12:01] [HoneywellHome] Loading accessory from cache: Downstairs Thermostat
[25/11/2020, 23:12:01] [HoneywellHome] Loading accessory from cache: xxxx's Room Thermostat
[25/11/2020, 23:12:01] [HoneywellHome] Loading accessory from cache: yyyy's Room IndoorAirSensor
[25/11/2020, 23:12:01] [HoneywellHome] Loading accessory from cache: yyyy's Room IndoorAirSensor
[25/11/2020, 23:12:01] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: cf05c5ff-f6a0-4f30-a58b-3742f19db7c8
    at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:419:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:308:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:268:69)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:10)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[25/11/2020, 23:12:01] Got SIGTERM, shutting down Homebridge...

Repeat....

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Pi Homebridge",
        "username": "<removed>",
        "port": 51724,
        "pin": "<removed>"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "<removed>",
            "password": "<removed>",
            "options": [
                "Hide.SerialNumber"
            ],
            "platform": "myQ"
        },
        {
            "name": "HoneywellHome",
            "credentials": {
                "consumerKey": "<removed>",
                "consumerSecret": "<removed>",
                "refreshToken": "<removed>",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "thermostat": {
                    "hide_fan": true,
                    "thermostatSetpointStatus": "PermanentHold"
                },
                "roompriority": {
                    "priorityType": "PickARoom"
                }
            },
            "platform": "HoneywellHome"
        }
    ]
}
```

**Screenshots:**

(none)

**Thermostat Model:**

2x T10 Smart Home Thermostats
1x Honeywell Smart Room Sensor

# **Environment:**

- **Node.js Version**: v14.15.1
- **NPM Version**: 6.14.8
- **Homebridge Version**: 1.2.3
- **Homebridge Honeywell Home Plugin Version**: homebridge-honeywell-home v8.1.1 
- **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.34.0 
- **Operating System**: Raspbian GNU/Linux 10 (buster)

**Comment by ericingravity** [comment]
After trying a few things, I noticed after I install homebridge-honeywell-home the first time and restart homebridge, it "works". I can see all the devices on Accessories page. See [honeywell1.log](https://github.com/donavanbecker/homebridge-honeywell-home/files/5600720/honeywell1.log).

However, if I restart homebridge again, I get the errors on the first post which are similar but the stack trace is different. At this point I have to uninstall the plugin.

**Comment by ericingravity** [comment]
No stale. 😞

**Comment by donavanbecker** [comment]
@ericingravity, Thanks to @NorthernMan54. We have refactored the plugin to better catch these things and also assign the right read out for each sensors. Can you test the latest Beta?

**If you have Homebridge UI:**

<img width="709" alt="Screen Shot 2020-12-08 at 6 56 02 PM" src="https://user-images.githubusercontent.com/9875439/101559592-0dcf7500-3987-11eb-8ee3-9eee403cb645.png">
<img width="511" alt="Screen Shot 2020-12-08 at 6 55 53 PM" src="https://user-images.githubusercontent.com/9875439/101559608-13c55600-3987-11eb-872f-25a7ed2695ff.png">
<img width="512" alt="Screen Shot 2020-12-08 at 6 55 46 PM" src="https://user-images.githubusercontent.com/9875439/101559617-1922a080-3987-11eb-9792-d1f5098a5592.png">


**Manually:**
To install:
``` 
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```

To Revert:
``` 
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```

**Comment by ericingravity** [comment]
I installed the beta, and so far everything looks to be working. Thanks so much!

**Comment by donavanbecker** [comment]
`v8.2.0` has been released with a fix for this issue! 

Merry Christmas!
