### ISSUE TITLE
v9.0.0 - Read Only, Round

### ISSUE THREAD

**Issue by wtadler** [homebridge-plugins/homebridge-resideo#410]
I have added my Lyric Round thermostat to Homebridge using this plugin. I can reliably see the temperature and status, but can't change it. On previous versions I would get various errors, like "Request failed with status code 400," but I don't get those any more with the newest version of this plugin.

**To Reproduce:**

Try to change the temperature in HomeKit on iOS or MacOS.

**Expected behavior:**

I expect the temperature to change.

**Logs:**

```
[2/9/2021, 7:42:55 PM] [Homebridge UI] Homebridge restart request received
[2/9/2021, 7:42:56 PM] [Homebridge UI] No restart command defined, killing process...
[2/9/2021, 7:42:56 PM] [HB Supervisor] Stopping services...
[2/9/2021, 7:42:56 PM] Got SIGTERM, shutting down Homebridge...
[2/9/2021, 7:43:01 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/9/2021, 7:43:03 PM] [HB Supervisor] Homebridge Storage Path: /Users/wtadler/.homebridge
[2/9/2021, 7:43:03 PM] [HB Supervisor] Homebridge Config Path: /Users/wtadler/.homebridge/config.json
[2/9/2021, 7:43:03 PM] [HB Supervisor] Logging to /Users/wtadler/.homebridge/homebridge.log
[2/9/2021, 7:43:03 PM] [HB Supervisor] OS: Darwin 20.3.0 x64
[2/9/2021, 7:43:03 PM] [HB Supervisor] Node.js v14.15.4 /usr/local/bin/node
[2/9/2021, 7:43:03 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[2/9/2021, 7:43:03 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[2/9/2021, 7:43:05 PM] [Homebridge UI] Homebridge Config UI X v4.38.0 is listening on :: port 8581
[2/9/2021, 7:43:05 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[2/9/2021, 7:43:05 PM] [HB Supervisor] Started Homebridge v1.2.5 with PID: 74982
[2/9/2021, 7:43:05 PM] Loaded config.json with 2 accessories and 2 platforms.
[2/9/2021, 7:43:05 PM] ---
[2/9/2021, 7:43:05 PM] Loaded plugin: homebridge-config-ui-x@4.38.0
[2/9/2021, 7:43:05 PM] Registering platform 'homebridge-config-ui-x.config'
[2/9/2021, 7:43:05 PM] ---
[2/9/2021, 7:43:05 PM] Loaded plugin: homebridge-delay-switch@2.2.6
[2/9/2021, 7:43:05 PM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2/9/2021, 7:43:05 PM] ---
[2/9/2021, 7:43:06 PM] Loaded plugin: homebridge-honeywell-home@8.4.0
[2/9/2021, 7:43:06 PM] Registering platform 'homebridge-honeywell-home.HoneywellHome'
[2/9/2021, 7:43:06 PM] ---
[2/9/2021, 7:43:06 PM] Loaded plugin: homebridge-meross@3.4.1
[2/9/2021, 7:43:06 PM] Registering accessory 'homebridge-meross.Meross'
[2/9/2021, 7:43:06 PM] ---
[2/9/2021, 7:43:06 PM] Loading 2 platforms...
[2/9/2021, 7:43:06 PM] [Config] Initializing config platform...
[2/9/2021, 7:43:06 PM] [Config] Running in Service Mode
[2/9/2021, 7:43:06 PM] [HoneywellHome] Initializing HoneywellHome platform...
[2/9/2021, 7:43:06 PM] [HoneywellHome] Finished initializing platform: HoneywellHome
[2/9/2021, 7:43:06 PM] [HoneywellHome] Config OK
[2/9/2021, 7:43:06 PM] Loading 2 accessories...
[2/9/2021, 7:43:06 PM] [1.5h timer] Initializing DelaySwitch accessory...
[2/9/2021, 7:43:06 PM] [4h timer] Initializing DelaySwitch accessory...
[2/9/2021, 7:43:06 PM] [HoneywellHome] Loading accessory from cache: Thermostat Thermostat
[2/9/2021, 7:43:06 PM] [HoneywellHome] Executed didFinishLaunching callback
Setup Payload:
X-HM://0024BOKJDOH7F
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX │     
    └────────────┘     
                       
[2/9/2021, 7:43:06 PM] Homebridge v1.2.5 is running on port 51576.
[2/9/2021, 7:43:06 PM] [HoneywellHome] Got access token: XXX
[2/9/2021, 7:43:06 PM] [HoneywellHome] New refresh token: XXX
[2/9/2021, 7:43:06 PM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[2/9/2021, 7:43:07 PM] [HoneywellHome] Total Locations Found: 1
[2/9/2021, 7:43:07 PM] [HoneywellHome] Total Devices Found at  Home : 1
[2/9/2021, 7:43:07 PM] [HoneywellHome] {"locationID":XXX,"name":"Home","streetAddress":"XXX","city":"XXX","state":"XXX","country":"XXX","zipcode":"XXX","devices":[{"thermostatVersion":"02.02.20.00","scheduleStatus":"Resume","allowedTimeIncrements":15,"settings":{"homeSetPoints":{"homeHeatSP":72,"homeCoolSP":78,"units":"Fahrenheit"},"awaySetPoints":{"awayHeatSP":67,"awayCoolSP":85,"smartCoolSP":80,"smartHeatSP":55,"useAutoSmart":false,"units":"Fahrenheit"},"hardwareSettings":{"brightness":6,"volume":10,"maxBrightness":10,"maxVolume":10},"fan":{"allowedModes":["Auto","On","Circulate"],"changeableValues":{"mode":"Auto"},"fanRunning":true},"temperatureMode":{"feelsLike":true,"air":true},"specialMode":{"autoChangeoverActive":false,"emergencyHeatActive":false}},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"TCC-2728972","userDefinedDeviceName":"Thermostat","name":"Thermostat","schedule":{"scheduleType":"Geofence"},"isAlive":true,"isUpgrading":false,"isProvisioned":false,"macID":"XXX","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"XXX","dataSyncStatus":"UnKnown","units":"Fahrenheit","indoorTemperature":72,"outdoorTemperature":42,"allowedModes":["Cool","Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":40,"maxHeatSetpoint":99,"minCoolSetpoint":40,"maxCoolSetpoint":99,"changeableValues":{"mode":"Heat","autoChangeoverActive":false,"emergencyHeatActive":false,"heatSetpoint":72,"coolSetpoint":78,"heatCoolMode":"Heat"},"operationStatus":{"mode":"Heat"},"smartAway":{"active":false,"timeOfDay":"00:00:00","durationInHours":1,"durationInDays":0,"lastUsedFormat":"DurationInHours","endsIn":"2020-09-14T15:30:00-04:00"},"indoorHumidity":20,"indoorHumidityStatus":"Measured","deviceModel":"Round"}],"users":[{"userID":2839893,"username":"XXX","firstname":"XXX","lastname":"XXX","created":1607534413,"deleted":-62135596800,"activated":true,"connectedHomeAccountExists":true,"locationRoleMapping":[{"locationID":XXX,"role":"Adult","locationName":"Home","status":1}],"isOptOut":"False","isCurrentUser":true}],"timeZoneId":"Eastern","timeZone":"Eastern Standard Time","ianaTimeZone":"America/New_York","daylightSavingTimeEnabled":true,"geoFences":[{"geofenceEnabled":true,"geoFenceID":XXX,"latitude":XXX,"longitude":XXX,"radius":XXX,"geoOccupancy":{"withinFence":1,"outsideFence":0},"geoFenceNotificationEnabled":true}],"geoFenceEnabled":true,"predictiveAIREnabled":false,"comfortLevel":0,"geoFenceNotificationEnabled":true,"geoFenceNotificationTypeId":13,"configuration":{"faceRecognition":{"enabled":false,"maxPersons":2,"maxEtas":2,"maxEtaPersons":1,"schedules":[{"time":[{"start":"15:00:00","end":"17:00:00"}],"days":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]}]}},"stateName":"XXX"}
[2/9/2021, 7:43:07 PM] [HoneywellHome] {"thermostatVersion":"02.02.20.00","scheduleStatus":"Resume","allowedTimeIncrements":15,"settings":{"homeSetPoints":{"homeHeatSP":72,"homeCoolSP":78,"units":"Fahrenheit"},"awaySetPoints":{"awayHeatSP":67,"awayCoolSP":85,"smartCoolSP":80,"smartHeatSP":55,"useAutoSmart":false,"units":"Fahrenheit"},"hardwareSettings":{"brightness":6,"volume":10,"maxBrightness":10,"maxVolume":10},"fan":{"allowedModes":["Auto","On","Circulate"],"changeableValues":{"mode":"Auto"},"fanRunning":true},"temperatureMode":{"feelsLike":true,"air":true},"specialMode":{"autoChangeoverActive":false,"emergencyHeatActive":false}},"deviceClass":"Thermostat","deviceType":"Thermostat","deviceID":"TCC-2728972","userDefinedDeviceName":"Thermostat","name":"Thermostat","schedule":{"scheduleType":"Geofence"},"isAlive":true,"isUpgrading":false,"isProvisioned":false,"macID":"XXX","deviceSettings":{},"service":{"mode":"Up"},"deviceRegistrationDate":"2020-12-09T21:29:49.5666667","dataSyncStatus":"UnKnown","units":"Fahrenheit","indoorTemperature":72,"outdoorTemperature":42,"allowedModes":["Cool","Heat","Off"],"deadband":0,"hasDualSetpointStatus":false,"minHeatSetpoint":40,"maxHeatSetpoint":99,"minCoolSetpoint":40,"maxCoolSetpoint":99,"changeableValues":{"mode":"Heat","autoChangeoverActive":false,"emergencyHeatActive":false,"heatSetpoint":72,"coolSetpoint":78,"heatCoolMode":"Heat"},"operationStatus":{"mode":"Heat"},"smartAway":{"active":false,"timeOfDay":"00:00:00","durationInHours":1,"durationInDays":0,"lastUsedFormat":"DurationInHours","endsIn":"2020-09-14T15:30:00-04:00"},"indoorHumidity":20,"indoorHumidityStatus":"Measured","deviceModel":"Round"}
[2/9/2021, 7:43:07 PM] [HoneywellHome] "TCC-2728972"
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device ID: TCC-2728972
[2/9/2021, 7:43:07 PM] [HoneywellHome] "Thermostat"
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device Type: Thermostat
[2/9/2021, 7:43:07 PM] [HoneywellHome] "Thermostat"
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device Class: Thermostat
[2/9/2021, 7:43:07 PM] [HoneywellHome] "Round"
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device Model: Round
[2/9/2021, 7:43:07 PM] [HoneywellHome] {"homeSetPoints":{"homeHeatSP":72,"homeCoolSP":78,"units":"Fahrenheit"},"awaySetPoints":{"awayHeatSP":67,"awayCoolSP":85,"smartCoolSP":80,"smartHeatSP":55,"useAutoSmart":false,"units":"Fahrenheit"},"hardwareSettings":{"brightness":6,"volume":10,"maxBrightness":10,"maxVolume":10},"fan":{"allowedModes":["Auto","On","Circulate"],"changeableValues":{"mode":"Auto"},"fanRunning":true},"temperatureMode":{"feelsLike":true,"air":true},"specialMode":{"autoChangeoverActive":false,"emergencyHeatActive":false}}
[2/9/2021, 7:43:07 PM] [HoneywellHome] {"allowedModes":["Auto","On","Circulate"],"changeableValues":{"mode":"Auto"},"fanRunning":true}
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device Fan Settings: [object Object]
[2/9/2021, 7:43:07 PM] [HoneywellHome] ["Auto","On","Circulate"]
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device Fan Allowed Modes: Auto,On,Circulate
[2/9/2021, 7:43:07 PM] [HoneywellHome] {"mode":"Auto"}
[2/9/2021, 7:43:07 PM] [HoneywellHome] Device Fan Changeable Values: [object Object]
[2/9/2021, 7:43:07 PM] [HoneywellHome] Discovered Thermostat Round - Home Thermostat
[2/9/2021, 7:43:07 PM] [HoneywellHome] Restoring existing accessory from cache: Thermostat Thermostat DeviceID: TCC-2728972
[2/9/2021, 7:43:07 PM] [HoneywellHome] Round Thermostat Thermostat Heat - Device is Currently:  1
[2/9/2021, 7:43:07 PM] [HoneywellHome] Round Thermostat Thermostat - Device is in "Heat" mode
[2/9/2021, 7:43:07 PM] [HoneywellHome] Round Thermostat Thermostat - [ 'Cool', 'Heat', 'Off' ]
[2/9/2021, 7:43:07 PM] [HoneywellHome] Round Thermostat Thermostat - Only Show These Modes: [2,1,0]
[2/9/2021, 7:43:07 PM] [HoneywellHome] Round UDID: Thermostat-TCC-2728972-Round
[2/9/2021, 7:45:31 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetHeatingCoolingState: 1
[2/9/2021, 7:45:31 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 22, Changing Heat: 22, Current Cool: 25.5, Changing Cool: 25.5

[1ST ATTEMPT TO CHANGE TEMPERATURE THROUGH HOME APP]

[2/9/2021, 7:45:50 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetTemperature: 24
[2/9/2021, 7:45:50 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 22, Changing Heat: 22, Current Cool: 25.5, Changing Cool: 25.5

[2ND ATTEMPT TO CHANGE TEMPERATURE THROUGH HOME APP]

[2/9/2021, 7:45:59 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetTemperature: 25
[2/9/2021, 7:45:59 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 22, Changing Heat: 22, Current Cool: 25.5, Changing Cool: 25.5

```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge AAD0",
        "username": "XXX",
        "port": 51576,
        "pin": "XXX",
        "devicediscovery": true
    },
    "accessories": [
        {
            "name": "1.5h timer",
            "delay": 5400000,
            "disableSensor": true,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "4h timer",
            "delay": 14400000,
            "disableSensor": true,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config",
            "devicediscovery": true
        },
        {
            "name": "HoneywellHome",
            "devicediscovery": true,
            "credentials": {
                "consumerKey": "XXX",
                "consumerSecret": "XXX",
                "refreshToken": "XXX",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "thermostat": {
                    "hide_fan": true,
                    "thermostatSetpointStatus": "PermanentHold"
                },
                "roompriority": {
                    "priorityType": "PickARoom"
                }
            },
            "platform": "HoneywellHome"
        }
    ]
}
```

**Device & Model:**

Honeywell Lyric Round

# **Environment:**

- **Node.js Version**: v14.15.4
- **NPM Version**: 7.5.2
- **Homebridge Version**: 1.2.5
- **Homebridge Honeywell Home Plugin Version**: 8.4.0
- **Homebridge Config UI X Plugin Version**: 4.38.0
- **Operating System**: MacOS

**Comment by donavanbecker** [comment]
@wtadler When looking at those logs it doesn't look like you made change to the thermostat in the home app? It says current 25.5 and changing 25.5

Can you try a more drastic change?
Also what Is your Devices Units? Fahrenheit or Celsius￼

**Comment by wtadler** [comment]
You can see that it changes the `TargetTemperature`. I changed it a bit more drastically here:
```
[CHANGE TO 80°F]
[2/10/2021, 12:40:24 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetHeatingCoolingState: 1
[2/10/2021, 12:40:25 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 23.5, Changing Heat: 23.5, Current Cool: 25.5, Changing Cool: 25.5
[2/10/2021, 12:40:29 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetTemperature: 26.5
[2/10/2021, 12:40:29 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 23.5, Changing Heat: 23.5, Current Cool: 25.5, Changing Cool: 25.5

[CHANGE TO 86°F]
[2/10/2021, 12:40:35 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetHeatingCoolingState: 1
[2/10/2021, 12:40:35 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 23.5, Changing Heat: 23.5, Current Cool: 25.5, Changing Cool: 25.5
[2/10/2021, 12:40:39 PM] [HoneywellHome] Round Thermostat Thermostat - Set TargetTemperature: 30
[2/10/2021, 12:40:39 PM] [HoneywellHome] T9 Thermostat Thermostat Current Mode: 1, Changing Mode: 1, Current Heat: 23.5, Changing Heat: 23.5, Current Cool: 25.5, Changing Cool: 25.5
```

The units ares set as Fahrenheit, as you can see in the device info if you search. But it appears to be showing a rounded-to-nearest-half Celsius, like you noticed in #378.

**Comment by donavanbecker** [comment]
Please see #414.

**Comment by donavanbecker** [comment]
@wtadler what logs are you getting with the Beta?

**Comment by donavanbecker** [comment]
@wtadler can you try the latest beta: `8.5.1-beta.2`

**Comment by wtadler** [comment]
Tried it. Looks like it's now getting new access and refresh tokens each time I read, and a `Request failed with status code 400` when I try to write?


```
[2/11/2021, 6:25:50 PM] [HoneywellHome] Thermostat Thermostat Thermostat - Set TargetHeatingCoolingState: 1
[2/11/2021, 6:25:51 PM] [HoneywellHome] Sending request for Thermostat Thermostat to Honeywell API. mode: Heat coolSetpoint: 78 heatSetpoint: 72 thermostatSetpointStatus: PermanentHold
[2/11/2021, 6:25:51 PM] [HoneywellHome] Thermostat Thermostat Thermostat pushChanges - {"mode":"Heat","thermostatSetpointStatus":"PermanentHold","autoChangeoverActive":false,"heatSetpoint":72,"coolSetpoint":78}
[2/11/2021, 6:25:52 PM] [HoneywellHome] "Request failed with status code 400"
[2/11/2021, 6:25:52 PM] [HoneywellHome] Thermostat Thermostat Thermostat - {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/usr/local/lib/node_modules/homebridge-honeywell-home/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/homebridge-honeywell-home/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-honeywell-home/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"https://api.honeywell.com/v2/devices/thermostats/TCC-2728972","method":"post","data":"{\"mode\":\"Heat\",\"thermostatSetpointStatus\":\"PermanentHold\",\"autoChangeoverActive\":false,\"heatSetpoint\":72,\"coolSetpoint\":78}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer XXX","User-Agent":"axios/0.21.1","Content-Length":123},"params":{"locationId":2417661,"apikey":"XXX"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2/11/2021, 6:25:52 PM] [HoneywellHome] Got access token: AAAA
[2/11/2021, 6:25:52 PM] [HoneywellHome] New refresh token: BBBB
[2/11/2021, 6:25:52 PM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[2/11/2021, 6:25:56 PM] [HoneywellHome] Thermostat Thermostat Thermostat - Set TargetTemperature: 25
[2/11/2021, 6:25:56 PM] [HoneywellHome] Sending request for Thermostat Thermostat to Honeywell API. mode: Heat coolSetpoint: 78 heatSetpoint: 77 thermostatSetpointStatus: PermanentHold
[2/11/2021, 6:25:56 PM] [HoneywellHome] Thermostat Thermostat Thermostat pushChanges - {"mode":"Heat","thermostatSetpointStatus":"PermanentHold","autoChangeoverActive":false,"heatSetpoint":77,"coolSetpoint":78}
[2/11/2021, 6:25:57 PM] [HoneywellHome] "Request failed with status code 400"
[2/11/2021, 6:25:57 PM] [HoneywellHome] Thermostat Thermostat Thermostat - {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/usr/local/lib/node_modules/homebridge-honeywell-home/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/homebridge-honeywell-home/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-honeywell-home/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"https://api.honeywell.com/v2/devices/thermostats/TCC-2728972","method":"post","data":"{\"mode\":\"Heat\",\"thermostatSetpointStatus\":\"PermanentHold\",\"autoChangeoverActive\":false,\"heatSetpoint\":77,\"coolSetpoint\":78}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer "","User-Agent":"axios/0.21.1","Content-Length":123},"params":{"locationId":2417661,"apikey":"XXX"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2/11/2021, 6:25:57 PM] [HoneywellHome] Got access token: CCCC
[2/11/2021, 6:25:57 PM] [HoneywellHome] New refresh token: DDDD
[2/11/2021, 6:25:57 PM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.

```

**Comment by donavanbecker** [comment]
@wtadler sorry for not focusing on this. I have published a beta that potentially will work with write to the API, based of [this](https://developer.honeywellhome.com/content/getting-started-guide). Can you give it a try?

Beta: `v9.4.2-beta.1`

**Comment by donavanbecker** [comment]
#554
